
# dataframe csv with clade alignment info
clades: 'input/clades.txt'

macse:
  fasta_ext: fasta
  other: 

raxml:
  executable: raxmlHPC-PTHREADS
  model: GTRCAT
  algorithm: a
  seed: 1
  bootstraps: autoMRE
  other: 

threads:
  raxml: 8
  macse: 8
mem_mb:
  raxml: 8000
  macse: 8000