
# dataframe csv with clade alignment info
clades: 'input/clades.txt'


raxml:
  executable: raxmlHPC-PTHREADS
  model: GTRCAT
  algorithm: a
  seed: 1
  bootstraps: autoMRE
  other: 

threads:
  raxml: 8
mem_mb:
  raxml: 8000
